"""
live_sync.py

This script connects NVIDIA Isaac Sim to the Farmbase AI Engine via WebSocket.
It drives the AMR Base and the Robotic Arm (IK) in real-time based on the 
AI Engine's kinematics state machine.

Instructions:
1. Start the Farmbase FastAPI backend (uvicorn main:app)
2. Open NVIDIA Isaac Sim
3. Open the scene generated by `scene_builder_standalone.py` (e.g. farm.usd)
4. Open the Isaac Sim Script Editor (Window -> Script Editor)
5. Paste this script and run it.

Note: You may need to install `websockets` in your Isaac Sim python environment:
> python.bat -m pip install websockets
"""

import asyncio
import json
import numpy as np
import websockets
from pxr import Gf, UsdGeom
import omni.appwindow
from omni.isaac.core.prims import XFormPrim
from omni.isaac.core.utils.rotations import euler_angles_to_quat

# Try importing Franka and its RMPFlow controller for IK
HAS_FRANKA = False
try:
    from omni.isaac.franka import Franka
    from omni.isaac.franka.controllers import RMPFlowController
    HAS_FRANKA = True
except ImportError:
    pass

uri = "ws://localhost:8000/ws"

async def sync_loop():
    print(f"Attempting to connect to Farmbase AI Engine at {uri}...")
    
    # 1. Grab references to the USD primes
    amr_base = XFormPrim("/World/Farm/AMR_Base")
    
    franka = None
    controller = None
    
    if HAS_FRANKA:
        try:
            # Re-wrap the built-in Franka that scene_builder spawned
            franka = Franka(prim_path="/World/Farm/AMR_Base/FrankaArm", name="franka")
            franka.initialize()
            controller = RMPFlowController(name="franka_controller", robot_articulation=franka)
            print("Franka RMPFlow Controller initialized for IK.")
        except Exception as e:
            print(f"Warning: Franka initialization failed: {e}")
            HAS_FRANKA = False

    try:
        async with websockets.connect(uri) as websocket:
            print("✅ Live Sync Connected to Farmbase AI Engine!")
            
            # The async generator allows us to loop without blocking the Isaac UI thread
            while True:
                msg = await websocket.recv()
                data = json.loads(msg)
                
                if "computed" in data and "robotState" in data["computed"]:
                    state = data["computed"]["robotState"]
                    
                    # AI Coordinate mapping:
                    # Ground plane: X, Z (in python) -> X, Y (in Isaac Sim)
                    # Height: Y (in python) -> Z (in Isaac Sim)
                    bx = state.get("baseX", 0.0)
                    bz = state.get("baseZ", 0.0)
                    byaw = state.get("baseYaw", 0.0)
                    
                    # Target (Strawberry) coordinates
                    tx = state.get("targetX", 0.0)
                    tz = state.get("targetZ", 0.0)
                    ty = state.get("targetY", 0.0)
                    
                    phase = state.get("phase", "IDLE")

                    # --- 1. Move AMR Base ---
                    if amr_base.is_valid():
                        # The Z rotation is mapped directly, assuming scene builder standard (Z-up)
                        quat = euler_angles_to_quat(np.array([0, 0, byaw]))
                        amr_base.set_world_pose(
                            position=np.array([bx, bz, 0.15]), # 0.15 is the height offset of the chassis
                            orientation=quat
                        )

                    # --- 2. Move Robotic Arm (IK) ---
                    if HAS_FRANKA and controller:
                        if phase in ["APPROACH", "CUT"]:
                            # Tell Franka's end-effector to go to the strawberry
                            # Note: The target position is in world space
                            actions = controller.forward(
                                target_end_effector_position=np.array([tx, tz, ty]),
                                target_end_effector_orientation=euler_angles_to_quat(np.array([0, np.pi/2, byaw])) 
                            )
                            franka.apply_action(actions)
                        elif phase in ["RETRACT", "TRANSIT", "RAIL_MOVE"]:
                            # Return to a safe transport pose
                            default_pose_actions = controller.forward(
                                target_end_effector_position=np.array([bx, bz, 0.60]),
                                target_end_effector_orientation=euler_angles_to_quat(np.array([0, 0, byaw]))
                            )
                            franka.apply_action(default_pose_actions)
                            
                # Yield control to Isaac Sim's render loop to avoid freezing the GUI
                await asyncio.sleep(0.016)

    except ConnectionRefusedError:
        print(f"❌ Could not connect to {uri}. Make sure the AI Engine (uvicorn) is running.")
    except Exception as e:
        print(f"Live Sync Error: {e}")

# In Isaac Sim Script Editor, we just run the async loop
asyncio.ensure_future(sync_loop())
print("Live sync script launched in background task.")
